version: "3.7"
services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "C@sita2525"